simulation:
  mcts_simulations: 100
  keep_subtree: true
  parallel_search: false
  parallel:
    num_search_threads: 4
    virtual_loss: 3.0

uct:
  pb_c_base: 10000
  pb_c_init: 1.15

exploration:
  number_of_softmax_moves: 0
  epsilon_softmax_exploration: 0.0
  epsilon_random_exploration: 0.0
  value_factor: 1.0
