name: "alphazoo_connect_four"
backend: "alphazoo"

env:
  name: "connect_four"
  obs_space_format: "channels_last"
  kwargs: {}

algorithm:
  name: "alphazero"
  iterations: 500
  config:
    running:
      running_mode: "sequential"
      num_groups: 2
      workers_per_group: 3
      training_steps: 500
      early_fill_per_type: 100
      sequential:
        num_games_per_type_per_step: 12
    cache:
      enabled: true
      max_size: 8000
    learning:
      learning_method: "samples"
      replay_window_size: 10000
      value_loss: "SE"
      policy_loss: "CEL"
      samples:
        batch_size: 64
        num_samples: 128
    search:
      simulation:
        mcts_simulations: 100
        keep_subtree: true
      uct:
        pb_c_base: 10000
        pb_c_init: 1.15
      exploration:
        number_of_softmax_moves: 0
        epsilon_softmax_exploration: 0.04
        epsilon_random_exploration: 0.0001
        value_factor: 1.0
        root_exploration_distribution: "gamma"
        root_exploration_fraction: 0.20
        root_dist_alpha: 0.15
        root_dist_beta: 1.0
    scheduler:
      starting_lr: 0.001
      boundaries: [10000, 20000]
      gamma: 0.2

network:
  architecture: "MLPNet"
  hidden_layers: 3
  neurons_per_layer: 64
  head_layers: 2

eval_games: 100
eval_interval: 20
plot_interval: 25
info_interval: 50
eval_graph_split: 100
checkpoint_interval: 50


continue_training: false
# continue_from_iteration: 100