name: "example"
debug: false
game_config: "/path/to/config.yml"

algorithm:
  name: "ppo"
  iterations: 1000
  config:
    use_curiosity: false
    curiosity_coeff: 0.05

    num_env_runners: 0
    rollout_fragment_length: 128
    train_batch_size_per_learner: 256
    minibatch_size: 64
    num_epochs: 2
    lr: 
      - [0, 0.00004]
      - [512000, 0.00002]
      - [768000, 0.00001]
      - [1024000, 0.000005]
    gamma: 0.999
    entropy_coeff: 0.05
    vf_loss_coeff: 0.5
    clip_param: 0.2
    use_kl_loss: true
    kl_coeff: 0.2
    kl_target: 0.01

network:
  architecture: "ResNet"
  num_filters: 16
  num_blocks: 4
  hex: false


eval_games: 100
eval_interval: 15
eval_vs_previous: true
eval_graph_split: 500
plot_interval: 35

checkpoint_interval: 50
continue_training: false
# continue_from_iteration: 3000
stop_on_nan: true
info_interval: 100

