name: "example"

algorithm:
  name: "ppo"
  iterations: 500
  config:
    num_env_runners: 0
    rollout_fragment_length: 64
    train_batch_size_per_learner: 256
    minibatch_size: 16
    lr: 0.0005
    gamma: 0.995
    entropy_coeff: 0.01

network:
  architecture: "ResNet"
  num_filters: 64
  num_blocks: 3
  batch_norm: false
  hex: false

game_config: "/path/to/config.yml"
eval_interval: 20
eval_games: 50
plot_interval: 50
checkpoint_interval: 100
continue_training: false
debug: false